version: "3.8"

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./symfony:/var/www/html
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - symfony_network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge
  db_network:
    external: true
