version: "3.8"

services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

  adminer:
    build:
      context: ./adminer
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - db_network

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge
